-- =======================================================
-- CSMS_DB_FULL_MERGED.sql
-- Generated by merging uploaded SQL files into one runnable script.
-- Recommended run order used:
-- 01 create_table -> 02 database_update -> 03 testData ->
-- 04 permission_migration -> 05 waiter/barista -> 06 testOrderData
--
-- Note: create_table drops and recreates CSMS_DB.
-- Run with SQL Server/SSMS or sqlcmd, for example:
-- sqlcmd -S localhost -U sa -P 123 -i CSMS_DB_FULL_MERGED.sql -f 65001
-- =======================================================



-- =======================================================
-- BEGIN 01: 01_create_table (create_table(3).sql)
-- =======================================================
-- =======================================================
-- 1. Create Database
-- =======================================================
SET QUOTED_IDENTIFIER ON;
GO
USE master;
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'CSMS_DB')
BEGIN
    DROP DATABASE CSMS_DB;
END
GO

CREATE DATABASE CSMS_DB;
GO

USE CSMS_DB;
GO

-- =======================================================
-- 2. Create Tables (With Foreign Keys)
-- =======================================================

-- 2.1 Role Table
CREATE TABLE [Role] (
    RoleID INT IDENTITY(1,1) PRIMARY KEY,
    RoleName NVARCHAR(50) NOT NULL UNIQUE
);

-- 2.2 Permission Table
CREATE TABLE [Permission] (
    PermissionID INT IDENTITY(1,1) PRIMARY KEY,
    PermissionName VARCHAR(100) NOT NULL UNIQUE,
    Description NVARCHAR(255) NULL
);

-- 2.3 RolePermission Table
CREATE TABLE [RolePermission] (
    RoleID INT NOT NULL,
    PermissionID INT NOT NULL,
    PRIMARY KEY (RoleID, PermissionID),
    CONSTRAINT FK_RolePermission_Role 
        FOREIGN KEY (RoleID) REFERENCES [Role](RoleID),
    CONSTRAINT FK_RolePermission_Permission 
        FOREIGN KEY (PermissionID) REFERENCES [Permission](PermissionID)
);

-- 2.4 Tier Table
CREATE TABLE [Tier] (
    TierID INT IDENTITY(1,1) PRIMARY KEY,
    TierName NVARCHAR(50) NOT NULL UNIQUE,
    MinPoints INT NOT NULL DEFAULT 0,
    DiscountPercent INT NOT NULL DEFAULT 0,
    CONSTRAINT CHK_Tier_MinPoints CHECK (MinPoints >= 0),
    CONSTRAINT CHK_Tier_Discount CHECK (DiscountPercent BETWEEN 0 AND 100)
);

-- 2.5 Staff Table
CREATE TABLE [Staff] (
    StaffID INT IDENTITY(1,1) PRIMARY KEY,
    Username VARCHAR(50) UNIQUE NOT NULL,
    [Password] VARCHAR(255) NOT NULL,
    PIN_Code VARCHAR(255) NOT NULL,
    FullName NVARCHAR(100) NOT NULL,
    RoleID INT NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,

    FailedPINAttempts INT NOT NULL DEFAULT 0,
    LockedUntil DATETIME NULL,
    LastFailedPINAt DATETIME NULL,

    CONSTRAINT FK_Staff_Role 
        FOREIGN KEY (RoleID) REFERENCES [Role](RoleID)
);

-- 2.6 Member Table
CREATE TABLE [Member] (
    MemberID INT IDENTITY(1,1) PRIMARY KEY,
    FullName NVARCHAR(100) NOT NULL,
    Phone VARCHAR(15) UNIQUE NOT NULL,
    RewardPoints INT NOT NULL DEFAULT 0,
    TierID INT NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    PasswordHash VARCHAR(255) NULL,
    CONSTRAINT FK_Member_Tier 
        FOREIGN KEY (TierID) REFERENCES [Tier](TierID)
);

-- 2.7 Category Table
CREATE TABLE [Category] (
    CategoryID INT IDENTITY(1,1) PRIMARY KEY,
    CategoryName NVARCHAR(100) NOT NULL UNIQUE
);

-- 2.8 Product Table
CREATE TABLE [Product] (
    ProductID INT IDENTITY(1,1) PRIMARY KEY,
    ProductName NVARCHAR(150) NOT NULL,
    Price INT NOT NULL CHECK (Price >= 0),
    ImageURL VARCHAR(255) NULL,
    [Status] BIT NOT NULL DEFAULT 1,
    CategoryID INT NOT NULL,
    CONSTRAINT FK_Product_Category 
        FOREIGN KEY (CategoryID) REFERENCES [Category](CategoryID)
);

-- 2.9 Tables Table
CREATE TABLE [Tables] (
    TableID INT IDENTITY(1,1) PRIMARY KEY,
    TableName NVARCHAR(50) NOT NULL UNIQUE,
    [Status] VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    QRToken VARCHAR(64) NULL,
    CONSTRAINT CHK_Table_Status 
        CHECK ([Status] IN ('AVAILABLE', 'OCCUPIED', 'CLEANING'))
);

-- 2.10 Voucher Table
CREATE TABLE [Voucher] (
    VoucherID INT IDENTITY(1,1) PRIMARY KEY,
    VoucherCode VARCHAR(50) NOT NULL UNIQUE,
    DiscountAmount INT NULL,
    DiscountPercent INT NULL,
    MinTierRequired INT NULL,
    ExpiryDate DATETIME NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,

    CONSTRAINT FK_Voucher_Tier 
        FOREIGN KEY (MinTierRequired) REFERENCES [Tier](TierID),

    CONSTRAINT CHK_Voucher_Discount CHECK (
        (DiscountAmount IS NOT NULL AND DiscountPercent IS NULL AND DiscountAmount > 0)
        OR
        (DiscountAmount IS NULL AND DiscountPercent IS NOT NULL AND DiscountPercent BETWEEN 1 AND 100)
    )
);

-- 2.11 Orders Table
CREATE TABLE [Orders] (
    OrderID INT IDENTITY(1,1) PRIMARY KEY,
    OrderDate DATETIME NOT NULL DEFAULT GETDATE(),
    TotalAmount INT NOT NULL DEFAULT 0,
    DiscountAmount INT NOT NULL DEFAULT 0,
    FinalAmount AS (TotalAmount - DiscountAmount),

    PaymentMethod VARCHAR(20) NULL,
    TransactionID VARCHAR(100) NULL,

    OrderSource VARCHAR(20) NOT NULL DEFAULT 'POS',
    OrderStatus VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    PaymentStatus VARCHAR(20) NOT NULL DEFAULT 'UNPAID',

    TableID INT NULL,
    CashierID INT NULL,
    MemberID INT NULL,
    VoucherID INT NULL,

    CONSTRAINT FK_Orders_Table 
        FOREIGN KEY (TableID) REFERENCES [Tables](TableID),

    CONSTRAINT FK_Orders_Cashier 
        FOREIGN KEY (CashierID) REFERENCES [Staff](StaffID),

    CONSTRAINT FK_Orders_Member 
        FOREIGN KEY (MemberID) REFERENCES [Member](MemberID),

    CONSTRAINT FK_Orders_Voucher 
        FOREIGN KEY (VoucherID) REFERENCES [Voucher](VoucherID),

    CONSTRAINT CHK_Order_Source 
        CHECK (OrderSource IN ('QR', 'POS', 'WAITER')),

    CONSTRAINT CHK_Order_Status 
        CHECK (OrderStatus IN ('PENDING', 'PREPARING', 'READY', 'COMPLETED', 'CANCELLED')),

    CONSTRAINT CHK_Payment_Status 
        CHECK (PaymentStatus IN ('UNPAID', 'PENDING', 'PAID', 'FAILED')),

    CONSTRAINT CHK_Payment_Method 
        CHECK (PaymentMethod IS NULL OR PaymentMethod IN ('CASH', 'VIETQR')),

    CONSTRAINT CHK_Order_Discount 
        CHECK (DiscountAmount >= 0 AND DiscountAmount <= TotalAmount)
);

-- TransactionID chi can duy nhat khi co gia tri (cho phep nhieu don NULL)
CREATE UNIQUE NONCLUSTERED INDEX UQ_Orders_TransactionID
    ON [Orders](TransactionID) WHERE TransactionID IS NOT NULL;

-- 2.12 OrderDetail Table
CREATE TABLE [OrderDetail] (
    DetailID INT IDENTITY(1,1) PRIMARY KEY,
    OrderID INT NOT NULL,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL CHECK (Quantity > 0),
    UnitPrice INT NOT NULL CHECK (UnitPrice >= 0),
    Subtotal AS (Quantity * UnitPrice),
    Note NVARCHAR(255) NULL,
    ItemStatus VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    CONSTRAINT FK_OrderDetail_Orders 
        FOREIGN KEY (OrderID) REFERENCES [Orders](OrderID),

    CONSTRAINT FK_OrderDetail_Product 
        FOREIGN KEY (ProductID) REFERENCES [Product](ProductID),

    CONSTRAINT CHK_Item_Status 
        CHECK (ItemStatus IN ('PENDING', 'PREPARING', 'READY', 'SERVED'))
);

-- 2.13 Shift Table
CREATE TABLE [Shift] (
    ShiftID INT IDENTITY(1,1) PRIMARY KEY,
    StartTime DATETIME NOT NULL DEFAULT GETDATE(),
    EndTime DATETIME NULL,
    StartingCash INT NOT NULL DEFAULT 0,
    ActualCash INT NULL,
    SystemCalculatedCash INT NULL,
    CashierID INT NOT NULL,

    CONSTRAINT FK_Shift_Cashier 
        FOREIGN KEY (CashierID) REFERENCES [Staff](StaffID)
);

-- 2.14 Inventory Table
CREATE TABLE [Inventory] (
    IngredientID INT IDENTITY(1,1) PRIMARY KEY,
    IngredientName NVARCHAR(100) NOT NULL,
    StockQuantity DECIMAL(10,2) NOT NULL DEFAULT 0,
    MinStockLevel DECIMAL(10,2) NOT NULL DEFAULT 0,
    Unit NVARCHAR(20) NOT NULL
);

-- 2.15 Recipe Table
CREATE TABLE [Recipe] (
    ProductID INT NOT NULL,
    IngredientID INT NOT NULL,
    QuantityNeeded DECIMAL(10,2) NOT NULL CHECK (QuantityNeeded > 0),

    PRIMARY KEY (ProductID, IngredientID),

    CONSTRAINT FK_Recipe_Product 
        FOREIGN KEY (ProductID) REFERENCES [Product](ProductID),

    CONSTRAINT FK_Recipe_Inventory 
        FOREIGN KEY (IngredientID) REFERENCES [Inventory](IngredientID)
);

-- 2.16 StaffSession Table
CREATE TABLE [StaffSession] (
    SessionID INT IDENTITY(1,1) PRIMARY KEY,
    StaffID INT NOT NULL,
    LoginTime DATETIME NOT NULL DEFAULT GETDATE(),
    LogoutTime DATETIME NULL,
    DeviceName NVARCHAR(100) NULL,
    IsActive BIT NOT NULL DEFAULT 1,

    CONSTRAINT FK_StaffSession_Staff 
        FOREIGN KEY (StaffID) REFERENCES [Staff](StaffID)
);

-- 2.17 RewardPointTransaction Table
CREATE TABLE [RewardPointTransaction] (
    PointTransactionID INT IDENTITY(1,1) PRIMARY KEY,
    MemberID INT NOT NULL,
    OrderID INT NULL,
    PointsChanged INT NOT NULL,
    Reason NVARCHAR(255) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),

    CONSTRAINT FK_PointTransaction_Member 
        FOREIGN KEY (MemberID) REFERENCES [Member](MemberID),

    CONSTRAINT FK_PointTransaction_Order 
        FOREIGN KEY (OrderID) REFERENCES [Orders](OrderID)
);

-- =======================================================
-- 3. Initial Seed Data (Tạo dữ liệu cơ bản)
-- =======================================================

-- Insert Roles
INSERT INTO [Role] (RoleName) VALUES ('MANAGER'), ('CASHIER'), ('BARISTA'), ('WAITER'), ('MEMBER');

-- Insert Tiers
INSERT INTO [Tier] (TierName, MinPoints, DiscountPercent) VALUES 
('Bronze', 0, 0), 
('Silver', 100, 5), 
('Gold', 500, 10);

-- Insert Demo Admin Staff (Password: 123456, PIN: 1234)
INSERT INTO [Staff] (Username, [Password], PIN_Code, FullName, RoleID, IsActive)
VALUES ('admin', 'hashed_password_here', 'hashed_pin_here', 'Manager Admin', 1, 1);
GO

UPDATE [Staff]
SET [Password] = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',
    PIN_Code = '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4'
WHERE Username = 'admin';
GO

-- 3.1 Categories
INSERT INTO [Category] (CategoryName) VALUES
(N'Cà phê'),
(N'Trà & Trà sữa'),
(N'Đá xay & Sữa chua'),
(N'Bánh & Ăn vặt');
GO

-- 3.2 Products
INSERT INTO [Product] (ProductName, Price, ImageURL, [Status], CategoryID) VALUES
(N'Cà phê đen đá',          25000, NULL, 1, 1),
(N'Cà phê sữa đá',          29000, NULL, 1, 1),
(N'Bạc xỉu',                32000, NULL, 1, 1),
(N'Cà phê muối',            35000, NULL, 1, 1),
(N'Espresso',               40000, NULL, 1, 1),
(N'Latte nóng',             45000, NULL, 1, 1),
(N'Cappuccino',             45000, NULL, 1, 1),
(N'Trà đào cam sả',         45000, NULL, 1, 2),
(N'Trà vải',                42000, NULL, 1, 2),
(N'Trà tắc mật ong',        35000, NULL, 1, 2),
(N'Trà sữa trân châu',      38000, NULL, 1, 2),
(N'Ô long sữa trân châu',   40000, NULL, 1, 2),
(N'Matcha đá xay',          50000, NULL, 1, 3),
(N'Cacao đá xay',           48000, NULL, 1, 3),
(N'Sữa chua việt quất',     42000, NULL, 1, 3),
(N'Tiramisu',               35000, NULL, 0, 4),
(N'Bông lan trứng muối',    30000, NULL, 1, 4),
(N'Croissant bơ',           29000, NULL, 1, 4);
GO

-- 3.3 Inventory
INSERT INTO [Inventory] (IngredientName, StockQuantity, MinStockLevel, Unit) VALUES
(N'Cà phê bột',              5000, 500, N'g'),
(N'Sữa đặc',                 4000, 400, N'ml'),
(N'Sữa tươi',                6000, 500, N'ml'),
(N'Đường',                   3000, 300, N'g'),
(N'Muối hồng',                500,  50, N'g'),
(N'Đào ngâm',                2000, 200, N'g'),
(N'Vải ngâm',                   0, 200, N'g'),
(N'Tắc tươi',                1000, 100, N'g'),
(N'Mật ong',                  800, 100, N'ml'),
(N'Trà đen',                 1500, 150, N'g'),
(N'Trà ô long',              1200, 150, N'g'),
(N'Trân châu',               2500, 250, N'g'),
(N'Bột matcha',               600, 100, N'g'),
(N'Bột cacao',                700, 100, N'g'),
(N'Sữa chua',                  40,   5, N'hộp'),
(N'Việt quất',                900, 100, N'g'),
(N'Bánh bông lan trứng muối',  12,   2, N'cái'),
(N'Bánh croissant',            10,   2, N'cái'),
(N'Bánh tiramisu',              8,   2, N'cái'),
(N'Cam vàng',                1500, 200, N'g'),
(N'Sả',                       800, 100, N'g');
GO

-- 3.4 Recipes
INSERT INTO [Recipe] (ProductID, IngredientID, QuantityNeeded) VALUES
(1, 1, 20),
(2, 1, 20), (2, 2, 30),
(3, 1, 10), (3, 2, 40), (3, 3, 60),
(4, 1, 20), (4, 2, 30), (4, 5, 3),
(5, 1, 18),
(6, 1, 18), (6, 3, 150),
(7, 1, 18), (7, 3, 120),
(8, 10, 8), (8, 6, 40), (8, 20, 30), (8, 21, 10),
(9, 10, 8), (9, 7, 40),
(10, 10, 8), (10, 8, 30), (10, 9, 15),
(11, 10, 8), (11, 3, 100), (11, 12, 40),
(12, 11, 8), (12, 3, 100), (12, 12, 40),
(13, 13, 15), (13, 3, 100), (13, 4, 20),
(14, 14, 20), (14, 3, 100), (14, 4, 20),
(15, 15, 1), (15, 16, 30),
(16, 19, 1),
(17, 17, 1),
(18, 18, 1);
GO

-- 3.5 Tables + QR token rieng cho tung ban
INSERT INTO [Tables] (TableName, [Status], QRToken) VALUES
(N'Bàn 01',      'AVAILABLE', 'tb01-k3f7a9d2'),
(N'Bàn 02',      'AVAILABLE', 'tb02-m8x2q5w1'),
(N'Bàn 03',      'AVAILABLE', 'tb03-p4j9c6t8'),
(N'Bàn 04',      'AVAILABLE', 'tb04-r7v1z3n6'),
(N'Bàn 05',      'AVAILABLE', 'tb05-s2h8b4y7'),
(N'Bàn 06',      'AVAILABLE', 'tb06-d9g5e1u3'),
(N'Sân vườn 01', 'AVAILABLE', 'gd01-w6t3k8f2'),
(N'Sân vườn 02', 'AVAILABLE', 'gd02-q1n7m4x9');
GO

-- 3.6 Vouchers
INSERT INTO [Voucher] (VoucherCode, DiscountAmount, DiscountPercent, MinTierRequired, ExpiryDate, IsActive) VALUES
('CHAOBAN',     5000, NULL, NULL, '2027-12-31', 1),
('THANHVIEN15', NULL, 15,   1,    '2027-12-31', 1),
('GOLD20',      NULL, 20,   3,    '2027-12-31', 1);
GO

-- 3.7 Demo member
INSERT INTO [Member] (FullName, Phone, RewardPoints, TierID, IsActive, PasswordHash)
VALUES (N'Nguyễn Minh Anh', '0901234567', 120, 2,  1, '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92');
GO

PRINT 'create_table.sql DONE';
GO

-- =======================================================
-- END 01: 01_create_table
-- =======================================================


-- =======================================================
-- BEGIN 02: 02_database_update_qr_member_seed (database_update(2).sql)
-- =======================================================
-- =======================================================
-- CSMS - Update script: QR ordering, member login, seed data
-- Chay duoc nhieu lan (idempotent), khong xoa du lieu cu.
-- Run: sqlcmd -S localhost -U sa -P 123 -d CSMS_DB -i database_update.sql -f 65001
-- =======================================================
USE CSMS_DB;
GO

-- 1. Member: them cot mat khau de thanh vien dang nhap
IF COL_LENGTH('Member', 'PasswordHash') IS NULL
BEGIN
    ALTER TABLE [Member] ADD PasswordHash VARCHAR(255) NULL;
END
GO

-- 2. Tables: moi ban co mot ma QR token rieng
IF COL_LENGTH('Tables', 'QRToken') IS NULL
BEGIN
    ALTER TABLE [Tables] ADD QRToken VARCHAR(64) NULL;
END
GO

-- 2b. Sua loi UNIQUE(TransactionID): rang buoc UNIQUE thuong chi cho phep
--     1 dong NULL -> khong the tao don thu 2. Doi sang filtered unique index.
SET QUOTED_IDENTIFIER ON;
GO
DECLARE @uq NVARCHAR(128);
SELECT @uq = kc.name
FROM sys.key_constraints kc
JOIN sys.index_columns ic ON ic.object_id = kc.parent_object_id AND ic.index_id = kc.unique_index_id
JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id
WHERE kc.parent_object_id = OBJECT_ID('Orders') AND kc.[type] = 'UQ' AND c.name = 'TransactionID';
IF @uq IS NOT NULL
    EXEC('ALTER TABLE Orders DROP CONSTRAINT [' + @uq + ']');
IF NOT EXISTS (SELECT 1 FROM sys.indexes
               WHERE name = 'UQ_Orders_TransactionID' AND object_id = OBJECT_ID('Orders'))
    CREATE UNIQUE NONCLUSTERED INDEX UQ_Orders_TransactionID
        ON Orders(TransactionID) WHERE TransactionID IS NOT NULL;
GO

-- =======================================================
-- 3. Seed data (chi chen khi bang con trong)
-- =======================================================

-- 3.1 Categories
IF NOT EXISTS (SELECT 1 FROM [Category])
BEGIN
    INSERT INTO [Category] (CategoryName) VALUES
    (N'Cà phê'),
    (N'Trà & Trà sữa'),
    (N'Đá xay & Sữa chua'),
    (N'Bánh & Ăn vặt');
END
GO

-- 3.2 Products
IF NOT EXISTS (SELECT 1 FROM [Product])
BEGIN
    INSERT INTO [Product] (ProductName, Price, ImageURL, [Status], CategoryID) VALUES
    (N'Cà phê đen đá',          25000, NULL, 1, 1),
    (N'Cà phê sữa đá',          29000, NULL, 1, 1),
    (N'Bạc xỉu',                32000, NULL, 1, 1),
    (N'Cà phê muối',            35000, NULL, 1, 1),
    (N'Espresso',               40000, NULL, 1, 1),
    (N'Latte nóng',             45000, NULL, 1, 1),
    (N'Cappuccino',             45000, NULL, 1, 1),
    (N'Trà đào cam sả',         45000, NULL, 1, 2),
    (N'Trà vải',                42000, NULL, 1, 2),
    (N'Trà tắc mật ong',        35000, NULL, 1, 2),
    (N'Trà sữa trân châu',      38000, NULL, 1, 2),
    (N'Ô long sữa trân châu',   40000, NULL, 1, 2),
    (N'Matcha đá xay',          50000, NULL, 1, 3),
    (N'Cacao đá xay',           48000, NULL, 1, 3),
    (N'Sữa chua việt quất',     42000, NULL, 1, 3),
    (N'Tiramisu',               35000, NULL, 0, 4), -- ngung ban (Status = 0)
    (N'Bông lan trứng muối',    30000, NULL, 1, 4),
    (N'Croissant bơ',           29000, NULL, 1, 4);
END
GO

-- 3.3 Inventory (Vai ngam = 0 de demo mon het nguyen lieu)
IF NOT EXISTS (SELECT 1 FROM [Inventory])
BEGIN
    INSERT INTO [Inventory] (IngredientName, StockQuantity, MinStockLevel, Unit) VALUES
    (N'Cà phê bột',              5000, 500, N'g'),     -- 1
    (N'Sữa đặc',                 4000, 400, N'ml'),    -- 2
    (N'Sữa tươi',                6000, 500, N'ml'),    -- 3
    (N'Đường',                   3000, 300, N'g'),     -- 4
    (N'Muối hồng',                500,  50, N'g'),     -- 5
    (N'Đào ngâm',                2000, 200, N'g'),     -- 6
    (N'Vải ngâm',                   0, 200, N'g'),     -- 7 (HET HANG)
    (N'Tắc tươi',                1000, 100, N'g'),     -- 8
    (N'Mật ong',                  800, 100, N'ml'),    -- 9
    (N'Trà đen',                 1500, 150, N'g'),     -- 10
    (N'Trà ô long',              1200, 150, N'g'),     -- 11
    (N'Trân châu',               2500, 250, N'g'),     -- 12
    (N'Bột matcha',               600, 100, N'g'),     -- 13
    (N'Bột cacao',                700, 100, N'g'),     -- 14
    (N'Sữa chua',                  40,   5, N'hộp'),   -- 15
    (N'Việt quất',                900, 100, N'g'),     -- 16
    (N'Bánh bông lan trứng muối',  12,   2, N'cái'),   -- 17
    (N'Bánh croissant',            10,   2, N'cái'),   -- 18
    (N'Bánh tiramisu',              8,   2, N'cái'),   -- 19
    (N'Cam vàng',                1500, 200, N'g'),     -- 20
    (N'Sả',                       800, 100, N'g');     -- 21
END
GO

-- 3.4 Recipes
IF NOT EXISTS (SELECT 1 FROM [Recipe])
BEGIN
    INSERT INTO [Recipe] (ProductID, IngredientID, QuantityNeeded) VALUES
    (1, 1, 20),
    (2, 1, 20), (2, 2, 30),
    (3, 1, 10), (3, 2, 40), (3, 3, 60),
    (4, 1, 20), (4, 2, 30), (4, 5, 3),
    (5, 1, 18),
    (6, 1, 18), (6, 3, 150),
    (7, 1, 18), (7, 3, 120),
    (8, 10, 8), (8, 6, 40), (8, 20, 30), (8, 21, 10),
    (9, 10, 8), (9, 7, 40),                            -- Tra vai -> het vai ngam
    (10, 10, 8), (10, 8, 30), (10, 9, 15),
    (11, 10, 8), (11, 3, 100), (11, 12, 40),
    (12, 11, 8), (12, 3, 100), (12, 12, 40),
    (13, 13, 15), (13, 3, 100), (13, 4, 20),
    (14, 14, 20), (14, 3, 100), (14, 4, 20),
    (15, 15, 1), (15, 16, 30),
    (16, 19, 1),
    (17, 17, 1),
    (18, 18, 1);
END
GO

-- 3.5 Tables + QR token rieng cho tung ban
IF NOT EXISTS (SELECT 1 FROM [Tables])
BEGIN
    INSERT INTO [Tables] (TableName, [Status], QRToken) VALUES
    (N'Bàn 01',      'AVAILABLE', 'tb01-k3f7a9d2'),
    (N'Bàn 02',      'AVAILABLE', 'tb02-m8x2q5w1'),
    (N'Bàn 03',      'AVAILABLE', 'tb03-p4j9c6t8'),
    (N'Bàn 04',      'AVAILABLE', 'tb04-r7v1z3n6'),
    (N'Bàn 05',      'AVAILABLE', 'tb05-s2h8b4y7'),
    (N'Bàn 06',      'AVAILABLE', 'tb06-d9g5e1u3'),
    (N'Sân vườn 01', 'AVAILABLE', 'gd01-w6t3k8f2'),
    (N'Sân vườn 02', 'AVAILABLE', 'gd02-q1n7m4x9');
END
ELSE
BEGIN
    -- Bang da ton tai nhung chua co token thi sinh token theo TableID
    UPDATE [Tables]
    SET QRToken = CONCAT('tbl', TableID, '-', LOWER(CONVERT(VARCHAR(8), ABS(CHECKSUM(NEWID())) % 99999999)))
    WHERE QRToken IS NULL;
END
GO

-- 3.6 Vouchers (CHAOBAN: moi khach | THANHVIEN15: chi thanh vien | GOLD20: hang Gold)
IF NOT EXISTS (SELECT 1 FROM [Voucher])
BEGIN
    INSERT INTO [Voucher] (VoucherCode, DiscountAmount, DiscountPercent, MinTierRequired, ExpiryDate, IsActive) VALUES
    ('CHAOBAN',     5000, NULL, NULL, '2027-12-31', 1),
    ('THANHVIEN15', NULL, 15,   1,    '2027-12-31', 1),
    ('GOLD20',      NULL, 20,   3,    '2027-12-31', 1);
END
GO

-- 3.7 Demo member (phone: 0901234567 / password: 123456)
IF NOT EXISTS (SELECT 1 FROM [Member])
BEGIN
    INSERT INTO [Member] (FullName, Phone, RewardPoints, TierID, IsActive, PasswordHash)
    VALUES (N'Nguyễn Minh Anh', '0901234567', 120, 2,  1,
            '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92');
END
GO

PRINT 'database_update.sql DONE';
GO

-- =======================================================
-- END 02: 02_database_update_qr_member_seed
-- =======================================================


-- =======================================================
-- BEGIN 03: 03_testData_permissions_roles_staff (testData(1).sql)
-- =======================================================
USE CSMS_DB;
GO

INSERT INTO [Permission] (PermissionName, Description)
VALUES
('MANAGE_STAFF', 'Manage staff accounts'),
('MANAGE_ROLE', 'Manage staff roles'),
('VIEW_REPORT', 'View sales reports'),
('MANAGE_VOUCHER', 'Manage vouchers'),
('MANAGE_MEMBER', 'Manage members'),
('CREATE_ORDER', 'Create customer orders'),
('CONFIRM_PAYMENT', 'Confirm order payment'),
('VIEW_KITCHEN_ORDER', 'View kitchen orders'),
('UPDATE_ORDER_STATUS', 'Update order item status'),
('VIEW_STAFF_ORDERS', 'View staff order board'),
('MANAGE_TABLE_QR', 'Manage table QR codes'),
('CANCEL_ORDER', 'Cancel pendinga orders');

INSERT INTO [RolePermission] (RoleID, PermissionID)
SELECT r.RoleID, p.PermissionID
FROM [Role] r
CROSS JOIN [Permission] p
WHERE r.RoleName = 'MANAGER';

INSERT INTO [RolePermission] (RoleID, PermissionID)
SELECT r.RoleID, p.PermissionID
FROM [Role] r
JOIN [Permission] p 
    ON p.PermissionName IN (
        'CREATE_ORDER',
        'CONFIRM_PAYMENT',
        'VIEW_STAFF_ORDERS',
        'CANCEL_ORDER'
    )
WHERE r.RoleName = 'CASHIER';

INSERT INTO [RolePermission] (RoleID, PermissionID)
SELECT r.RoleID, p.PermissionID
FROM [Role] r
JOIN [Permission] p 
    ON p.PermissionName IN (
        'VIEW_KITCHEN_ORDER',
        'UPDATE_ORDER_STATUS',
        'VIEW_STAFF_ORDERS'
    )
WHERE r.RoleName = 'BARISTA';

INSERT INTO [RolePermission] (RoleID, PermissionID)
SELECT r.RoleID, p.PermissionID
FROM [Role] r
JOIN [Permission] p 
    ON p.PermissionName IN ('CREATE_ORDER')
WHERE r.RoleName = 'WAITER';

-- Demo staff de test phan quyen (mat khau: 123456, PIN: 1234)
INSERT INTO [Staff] (Username, [Password], PIN_Code, FullName, RoleID, IsActive)
SELECT v.Username, v.[Password], v.PIN_Code, v.FullName, r.RoleID, 1
FROM (VALUES
    ('cashier', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',
             '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4',
             N'Thu ngân Demo', 'CASHIER'),
    ('barista', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',
             '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4',
             N'Pha chế Demo', 'BARISTA'),
    ('waiter', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',
             '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4',
             N'Phục vụ Demo', 'WAITER')
) AS v(Username, [Password], PIN_Code, FullName, RoleName)
JOIN [Role] r ON r.RoleName = v.RoleName
WHERE NOT EXISTS (SELECT 1 FROM [Staff] s WHERE s.Username = v.Username);
SELECT s.Username, r.RoleName
FROM Staff s
JOIN Role r ON s.RoleID = r.RoleID
WHERE s.Username = 'admin';

GO

-- =======================================================
-- END 03: 03_testData_permissions_roles_staff
-- =======================================================


-- =======================================================
-- BEGIN 04: 04_permission_migration_idempotent (permission_migration(1).sql)
-- =======================================================
-- Chay file nay neu DB da ton tai tu truoc (bo qua neu vua tao moi bang create_table.sql + testData.sql)

USE CSMS_DB;
GO

INSERT INTO [Permission] (PermissionName, Description)
SELECT v.PermissionName, v.Description
FROM (VALUES
    ('VIEW_STAFF_ORDERS', N'View staff order board'),
    ('MANAGE_TABLE_QR', N'Manage table QR codes'),
    ('CANCEL_ORDER', N'Cancel pending orders')
) AS v(PermissionName, Description)
WHERE NOT EXISTS (
    SELECT 1 FROM [Permission] p WHERE p.PermissionName = v.PermissionName
);
GO

INSERT INTO [RolePermission] (RoleID, PermissionID)
SELECT r.RoleID, p.PermissionID
FROM [Role] r
CROSS JOIN [Permission] p
WHERE r.RoleName = 'MANAGER'
  AND p.PermissionName IN ('VIEW_STAFF_ORDERS', 'MANAGE_TABLE_QR', 'CANCEL_ORDER')
  AND NOT EXISTS (
      SELECT 1 FROM [RolePermission] rp
      WHERE rp.RoleID = r.RoleID AND rp.PermissionID = p.PermissionID
  );
GO

INSERT INTO [RolePermission] (RoleID, PermissionID)
SELECT r.RoleID, p.PermissionID
FROM [Role] r
JOIN [Permission] p ON p.PermissionName IN ('VIEW_STAFF_ORDERS', 'CANCEL_ORDER')
WHERE r.RoleName = 'CASHIER'
  AND NOT EXISTS (
      SELECT 1 FROM [RolePermission] rp
      WHERE rp.RoleID = r.RoleID AND rp.PermissionID = p.PermissionID
  );
GO

INSERT INTO [RolePermission] (RoleID, PermissionID)
SELECT r.RoleID, p.PermissionID
FROM [Role] r
JOIN [Permission] p ON p.PermissionName = 'VIEW_STAFF_ORDERS'
WHERE r.RoleName = 'BARISTA'
  AND NOT EXISTS (
      SELECT 1 FROM [RolePermission] rp
      WHERE rp.RoleID = r.RoleID AND rp.PermissionID = p.PermissionID
  );
GO

INSERT INTO [Staff] (Username, [Password], PIN_Code, FullName, RoleID, IsActive)
SELECT v.Username, v.[Password], v.PIN_Code, v.FullName, r.RoleID, 1
FROM (VALUES
    ('cashier', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',
             '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4',
             N'Thu ngân Demo', 'CASHIER'),
    ('barista', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',
             '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4',
             N'Pha chế Demo', 'BARISTA'),
    ('waiter', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',
             '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4',
             N'Phục vụ Demo', 'WAITER')
) AS v(Username, [Password], PIN_Code, FullName, RoleName)
JOIN [Role] r ON r.RoleName = v.RoleName
WHERE NOT EXISTS (SELECT 1 FROM [Staff] s WHERE s.Username = v.Username);
GO

-- =======================================================
-- END 04: 04_permission_migration_idempotent
-- =======================================================


-- =======================================================
-- BEGIN 05: 05_database_waiter_barista (database_waiter&barista(1).sql)
-- =======================================================
-- =======================================================
-- CSMS - Update script: thêm nhân viên Waiter và Barista
-- Chạy nhiều lần không lỗi, chỉ thêm nếu chưa có
-- =======================================================
USE CSMS_DB;
GO

-- 1. Thêm cột WaiterID và BaristaID vào Orders nếu chưa có
IF COL_LENGTH('Orders', 'WaiterID') IS NULL
BEGIN
    ALTER TABLE [Orders] ADD WaiterID INT NULL;
    ALTER TABLE [Orders] ADD CONSTRAINT FK_Orders_Waiter FOREIGN KEY (WaiterID) REFERENCES [Staff](StaffID);
END
GO

IF COL_LENGTH('Orders', 'BaristaID') IS NULL
BEGIN
    ALTER TABLE [Orders] ADD BaristaID INT NULL;
    ALTER TABLE [Orders] ADD CONSTRAINT FK_Orders_Barista FOREIGN KEY (BaristaID) REFERENCES [Staff](StaffID);
END
GO

-- 2. Seed data cho Staff: thêm demo Waiter và Barista nếu chưa có
IF NOT EXISTS (SELECT 1 FROM [Staff] WHERE Username = 'waiter1')
BEGIN
    INSERT INTO [Staff] (Username, [Password], PIN_Code, FullName, RoleID, IsActive)
    VALUES ('waiter1',
            '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', -- password: 123456
            '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4', -- pin: 1234
            N'Nguyễn Văn A (Waiter)',
            (SELECT RoleID FROM [Role] WHERE RoleName = 'WAITER'),
            1);
END
GO

IF NOT EXISTS (SELECT 1 FROM [Staff] WHERE Username = 'barista1')
BEGIN
    INSERT INTO [Staff] (Username, [Password], PIN_Code, FullName, RoleID, IsActive)
    VALUES ('barista1',
            '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', -- password: 123456
            '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4', -- pin: 1234
            N'Trần Thị B (Barista)',
            (SELECT RoleID FROM [Role] WHERE RoleName = 'BARISTA'),
            1);
END
GO

PRINT 'database_update_waiter_barista.sql DONE';
GO

-- =======================================================
-- END 05: 05_database_waiter_barista
-- =======================================================


-- =======================================================
-- BEGIN 06: 06_testOrderData_demo_orders (testOrderData(1).sql)
-- =======================================================
-- =======================================================
-- CSMS - Demo Order Data for Reports
-- Tao du lieu don hang demo de bao cao co noi dung hien thi.
-- Chay SAU create_table.sql, testData.sql, va database_update.sql
-- Run: sqlcmd -S localhost -U sa -P 123 -d CSMS_DB -i testOrderData.sql -f 65001
-- =======================================================
USE CSMS_DB;
GO

-- Chi chen khi chua co don hang nao
IF NOT EXISTS (SELECT 1 FROM [Orders])
BEGIN
    PRINT 'Inserting demo order data...';

    -- ==========================================
    -- Tao 25 don hang trong 15 ngay gan day
    -- CashierID = 1 (admin, MANAGER)
    -- MemberID = 1 (Nguyen Minh Anh)
    -- ==========================================

    -- Don 1: Hom nay, POS, CASH, khach le
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 8, CAST(CAST(GETDATE() AS DATE) AS DATETIME)), 74000, 0, 'CASH', NULL, 'POS', 'COMPLETED', 'PAID', 1, 1, NULL, NULL);

    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (SCOPE_IDENTITY(), 1, 1, 25000, NULL, 'SERVED'),
           (SCOPE_IDENTITY(), 8, 1, 45000, NULL, 'SERVED');

    -- Don 2: Hom nay, QR, VIETQR, thanh vien
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 9, CAST(CAST(GETDATE() AS DATE) AS DATETIME)), 125000, 5000, 'VIETQR', 'TXN-TODAY-001', 'QR', 'COMPLETED', 'PAID', 2, 1, 1, 1);

    DECLARE @oid2 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid2, 3, 2, 32000, NULL, 'SERVED'),
           (@oid2, 7, 1, 45000, NULL, 'SERVED'),
           (@oid2, 17, 1, 30000, NULL, 'SERVED');

    -- Don 3: Hom nay, WAITER, CASH
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 10, CAST(CAST(GETDATE() AS DATE) AS DATETIME)), 83000, 0, 'CASH', NULL, 'WAITER', 'COMPLETED', 'PAID', 3, 1, NULL, NULL);

    DECLARE @oid3 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid3, 2, 1, 29000, N'Ít đường', 'SERVED'),
           (@oid3, 11, 1, 38000, NULL, 'SERVED'),
           (@oid3, 17, 1, 30000, NULL, 'SERVED');

    -- Don 4: Hom qua, POS, VIETQR
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 14, CAST(DATEADD(DAY, -1, CAST(GETDATE() AS DATE)) AS DATETIME)), 190000, 0, 'VIETQR', 'TXN-Y1-001', 'POS', 'COMPLETED', 'PAID', 1, 1, 1, NULL);

    DECLARE @oid4 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid4, 5, 2, 40000, NULL, 'SERVED'),
           (@oid4, 6, 1, 45000, NULL, 'SERVED'),
           (@oid4, 13, 1, 50000, NULL, 'SERVED'),
           (@oid4, 18, 1, 29000, NULL, 'SERVED');

    -- Don 5: Hom qua, QR, CASH
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 16, CAST(DATEADD(DAY, -1, CAST(GETDATE() AS DATE)) AS DATETIME)), 67000, 0, 'CASH', NULL, 'QR', 'COMPLETED', 'PAID', 4, 1, NULL, NULL);

    DECLARE @oid5 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid5, 1, 1, 25000, NULL, 'SERVED'),
           (@oid5, 15, 1, 42000, NULL, 'SERVED');

    -- Don 6: 2 ngay truoc, POS, CASH, thanh vien
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 9, CAST(DATEADD(DAY, -2, CAST(GETDATE() AS DATE)) AS DATETIME)), 145000, 0, 'CASH', NULL, 'POS', 'COMPLETED', 'PAID', 2, 1, 1, NULL);

    DECLARE @oid6 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid6, 4, 2, 35000, NULL, 'SERVED'),
           (@oid6, 8, 1, 45000, NULL, 'SERVED'),
           (@oid6, 17, 1, 30000, NULL, 'SERVED');

    -- Don 7: 2 ngay truoc, WAITER, VIETQR
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 11, CAST(DATEADD(DAY, -2, CAST(GETDATE() AS DATE)) AS DATETIME)), 97000, 0, 'VIETQR', 'TXN-D2-001', 'WAITER', 'COMPLETED', 'PAID', 5, 1, NULL, NULL);

    DECLARE @oid7 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid7, 10, 1, 35000, NULL, 'SERVED'),
           (@oid7, 12, 1, 40000, NULL, 'SERVED'),
           (@oid7, 18, 1, 29000, NULL, 'SERVED');

    -- Don 8: 3 ngay truoc, QR, VIETQR
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 8, CAST(DATEADD(DAY, -3, CAST(GETDATE() AS DATE)) AS DATETIME)), 210000, 0, 'VIETQR', 'TXN-D3-001', 'QR', 'COMPLETED', 'PAID', 1, 1, 1, NULL);

    DECLARE @oid8 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid8, 6, 2, 45000, NULL, 'SERVED'),
           (@oid8, 7, 2, 45000, NULL, 'SERVED'),
           (@oid8, 17, 1, 30000, NULL, 'SERVED');

    -- Don 9: 3 ngay truoc, POS, CASH
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 15, CAST(DATEADD(DAY, -3, CAST(GETDATE() AS DATE)) AS DATETIME)), 54000, 0, 'CASH', NULL, 'POS', 'COMPLETED', 'PAID', 3, 1, NULL, NULL);

    DECLARE @oid9 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid9, 1, 1, 25000, NULL, 'SERVED'),
           (@oid9, 2, 1, 29000, NULL, 'SERVED');

    -- Don 10: 4 ngay truoc, POS, CASH
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 10, CAST(DATEADD(DAY, -4, CAST(GETDATE() AS DATE)) AS DATETIME)), 129000, 0, 'CASH', NULL, 'POS', 'COMPLETED', 'PAID', 1, 1, NULL, NULL);

    DECLARE @oid10 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid10, 3, 1, 32000, NULL, 'SERVED'),
           (@oid10, 8, 1, 45000, NULL, 'SERVED'),
           (@oid10, 14, 1, 48000, NULL, 'SERVED');

    -- Don 11: 5 ngay truoc, QR, VIETQR
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 13, CAST(DATEADD(DAY, -5, CAST(GETDATE() AS DATE)) AS DATETIME)), 170000, 5000, 'VIETQR', 'TXN-D5-001', 'QR', 'COMPLETED', 'PAID', 2, 1, 1, 1);

    DECLARE @oid11 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid11, 5, 2, 40000, NULL, 'SERVED'),
           (@oid11, 13, 1, 50000, NULL, 'SERVED'),
           (@oid11, 11, 1, 38000, NULL, 'SERVED');

    -- Don 12: 5 ngay truoc, WAITER, CASH
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 17, CAST(DATEADD(DAY, -5, CAST(GETDATE() AS DATE)) AS DATETIME)), 64000, 0, 'CASH', NULL, 'WAITER', 'COMPLETED', 'PAID', 6, 1, NULL, NULL);

    DECLARE @oid12 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid12, 1, 1, 25000, NULL, 'SERVED'),
           (@oid12, 10, 1, 35000, NULL, 'SERVED');

    -- Don 13: 7 ngay truoc, POS, VIETQR
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 9, CAST(DATEADD(DAY, -7, CAST(GETDATE() AS DATE)) AS DATETIME)), 250000, 0, 'VIETQR', 'TXN-D7-001', 'POS', 'COMPLETED', 'PAID', 1, 1, 1, NULL);

    DECLARE @oid13 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid13, 6, 2, 45000, NULL, 'SERVED'),
           (@oid13, 7, 2, 45000, NULL, 'SERVED'),
           (@oid13, 13, 1, 50000, NULL, 'SERVED'),
           (@oid13, 17, 1, 30000, NULL, 'SERVED');

    -- Don 14: 7 ngay truoc, QR, CASH
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 11, CAST(DATEADD(DAY, -7, CAST(GETDATE() AS DATE)) AS DATETIME)), 77000, 0, 'CASH', NULL, 'QR', 'COMPLETED', 'PAID', 3, 1, NULL, NULL);

    DECLARE @oid14 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid14, 2, 1, 29000, NULL, 'SERVED'),
           (@oid14, 14, 1, 48000, NULL, 'SERVED');

    -- Don 15: 10 ngay truoc, POS, CASH
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 14, CAST(DATEADD(DAY, -10, CAST(GETDATE() AS DATE)) AS DATETIME)), 155000, 0, 'CASH', NULL, 'POS', 'COMPLETED', 'PAID', 4, 1, NULL, NULL);

    DECLARE @oid15 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid15, 4, 1, 35000, NULL, 'SERVED'),
           (@oid15, 5, 1, 40000, NULL, 'SERVED'),
           (@oid15, 13, 1, 50000, NULL, 'SERVED'),
           (@oid15, 17, 1, 30000, NULL, 'SERVED');

    -- Don 16: 10 ngay truoc, WAITER, VIETQR
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 16, CAST(DATEADD(DAY, -10, CAST(GETDATE() AS DATE)) AS DATETIME)), 90000, 0, 'VIETQR', 'TXN-D10-001', 'WAITER', 'COMPLETED', 'PAID', 5, 1, 1, NULL);

    DECLARE @oid16 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid16, 6, 1, 45000, NULL, 'SERVED'),
           (@oid16, 8, 1, 45000, NULL, 'SERVED');

    -- Don 17: 12 ngay truoc, QR, VIETQR
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 10, CAST(DATEADD(DAY, -12, CAST(GETDATE() AS DATE)) AS DATETIME)), 138000, 0, 'VIETQR', 'TXN-D12-001', 'QR', 'COMPLETED', 'PAID', 2, 1, NULL, NULL);

    DECLARE @oid17 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid17, 3, 1, 32000, NULL, 'SERVED'),
           (@oid17, 12, 1, 40000, NULL, 'SERVED'),
           (@oid17, 11, 1, 38000, NULL, 'SERVED'),
           (@oid17, 18, 1, 29000, NULL, 'SERVED');

    -- Don 18: 14 ngay truoc, POS, CASH
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 8, CAST(DATEADD(DAY, -14, CAST(GETDATE() AS DATE)) AS DATETIME)), 95000, 0, 'CASH', NULL, 'POS', 'COMPLETED', 'PAID', 1, 1, NULL, NULL);

    DECLARE @oid18 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid18, 7, 1, 45000, NULL, 'SERVED'),
           (@oid18, 13, 1, 50000, NULL, 'SERVED');

    -- Don 19: 14 ngay truoc, QR, VIETQR, thanh vien
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 12, CAST(DATEADD(DAY, -14, CAST(GETDATE() AS DATE)) AS DATETIME)), 185000, 0, 'VIETQR', 'TXN-D14-001', 'QR', 'COMPLETED', 'PAID', 3, 1, 1, NULL);

    DECLARE @oid19 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid19, 6, 2, 45000, NULL, 'SERVED'),
           (@oid19, 5, 1, 40000, NULL, 'SERVED'),
           (@oid19, 8, 1, 45000, NULL, 'SERVED'),
           (@oid19, 17, 1, 30000, NULL, 'SERVED');

    -- Don 20: 18 ngay truoc, POS, CASH
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 15, CAST(DATEADD(DAY, -18, CAST(GETDATE() AS DATE)) AS DATETIME)), 70000, 0, 'CASH', NULL, 'POS', 'COMPLETED', 'PAID', 4, 1, NULL, NULL);

    DECLARE @oid20 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid20, 4, 1, 35000, NULL, 'SERVED'),
           (@oid20, 10, 1, 35000, NULL, 'SERVED');

    -- Don 21: 20 ngay truoc, WAITER, VIETQR
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 9, CAST(DATEADD(DAY, -20, CAST(GETDATE() AS DATE)) AS DATETIME)), 122000, 0, 'VIETQR', 'TXN-D20-001', 'WAITER', 'COMPLETED', 'PAID', 6, 1, NULL, NULL);

    DECLARE @oid21 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid21, 3, 2, 32000, NULL, 'SERVED'),
           (@oid21, 14, 1, 48000, NULL, 'SERVED'),
           (@oid21, 17, 1, 30000, NULL, 'SERVED');

    -- Don 22: 22 ngay truoc, QR, CASH
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 11, CAST(DATEADD(DAY, -22, CAST(GETDATE() AS DATE)) AS DATETIME)), 87000, 0, 'CASH', NULL, 'QR', 'COMPLETED', 'PAID', 2, 1, 1, NULL);

    DECLARE @oid22 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid22, 2, 1, 29000, NULL, 'SERVED'),
           (@oid22, 11, 1, 38000, NULL, 'SERVED'),
           (@oid22, 17, 1, 30000, NULL, 'SERVED');

    -- Don 23: 25 ngay truoc, POS, VIETQR
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 14, CAST(DATEADD(DAY, -25, CAST(GETDATE() AS DATE)) AS DATETIME)), 220000, 0, 'VIETQR', 'TXN-D25-001', 'POS', 'COMPLETED', 'PAID', 1, 1, 1, NULL);

    DECLARE @oid23 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid23, 5, 2, 40000, NULL, 'SERVED'),
           (@oid23, 6, 1, 45000, NULL, 'SERVED'),
           (@oid23, 7, 1, 45000, NULL, 'SERVED'),
           (@oid23, 13, 1, 50000, NULL, 'SERVED');

    -- Don 24: 27 ngay truoc, WAITER, CASH
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 16, CAST(DATEADD(DAY, -27, CAST(GETDATE() AS DATE)) AS DATETIME)), 58000, 0, 'CASH', NULL, 'WAITER', 'COMPLETED', 'PAID', 5, 1, NULL, NULL);

    DECLARE @oid24 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid24, 1, 1, 25000, NULL, 'SERVED'),
           (@oid24, 18, 1, 29000, NULL, 'SERVED');

    -- Don 25: 29 ngay truoc, POS, CASH
    INSERT INTO [Orders] (OrderDate, TotalAmount, DiscountAmount, PaymentMethod, TransactionID, OrderSource, OrderStatus, PaymentStatus, TableID, CashierID, MemberID, VoucherID)
    VALUES (DATEADD(HOUR, 10, CAST(DATEADD(DAY, -29, CAST(GETDATE() AS DATE)) AS DATETIME)), 115000, 0, 'CASH', NULL, 'POS', 'COMPLETED', 'PAID', 3, 1, NULL, NULL);

    DECLARE @oid25 INT = SCOPE_IDENTITY();
    INSERT INTO [OrderDetail] (OrderID, ProductID, Quantity, UnitPrice, Note, ItemStatus)
    VALUES (@oid25, 4, 1, 35000, NULL, 'SERVED'),
           (@oid25, 8, 1, 45000, NULL, 'SERVED'),
           (@oid25, 10, 1, 35000, NULL, 'SERVED');

    PRINT 'Inserted 25 demo orders successfully!';
END
ELSE
BEGIN
    PRINT 'Orders already exist, skipping demo order data.';
END
GO

PRINT 'testOrderData.sql DONE';
GO

-- =======================================================
-- END 06: 06_testOrderData_demo_orders
-- =======================================================

PRINT 'CSMS_DB_FULL_MERGED.sql DONE';
GO
